spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notifications
    username: notify
    password: notify

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: notification-storage

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379
