services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sber
    ports:
      - "5432:5432"

  api-gateway:
    image: yourdockerhub/api-gateway:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"

  email-service:
    image: yourdockerhub/email-service:latest
    depends_on:
      - kafka

  sms-service:
    image: yourdockerhub/sms-service:latest
    depends_on:
      - kafka

  push-service:
    image: yourdockerhub/push-service:latest
    depends_on:
      - kafka

  retry-service:
    image: yourdockerhub/retry-service:latest
    depends_on:
      - kafka

  notification-storage:
    image: yourdockerhub/notification-storage:latest
    depends_on:
      - postgres
    ports:
      - "8081:8080"
