name: build-service
on:
  workflow_call:
    inputs:
      service: {required: true, type: string}
      dir:     {required: true, type: string}
      image:   {required: true, type: string}
    secrets:
      DOCKER_USERNAME: {required: true}
      DOCKER_PASSWORD: {required: true}

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: svc-${{ inputs.service }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Build JAR
        run: ./gradlew ${{ inputs.service }}:clean ${{ inputs.service }}:build --no-daemon
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-buildx-action@v3
      - name: Tag meta
        id: m
        run: |
          SHA=${GITHUB_SHA::7}
          echo "tags=${{ inputs.image }}:${SHA},${{ inputs.image }}:latest" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dir }}/Dockerfile
          push: true
          tags: ${{ steps.m.outputs.tags }}
