name: CD - Docker Build & Push (multi-service)

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          push: true
          tags: yourdockerhub/api-gateway:latest

      - name: Build and push Email Service
        uses: docker/build-push-action@v5
        with:
          context: ./email-service
          push: true
          tags: yourdockerhub/email-service:latest

      - name: Build and push SMS Service
        uses: docker/build-push-action@v5
        with:
          context: ./sms-service
          push: true
          tags: yourdockerhub/sms-service:latest

      - name: Build and push Push Service
        uses: docker/build-push-action@v5
        with:
          context: ./push-service
          push: true
          tags: yourdockerhub/push-service:latest

      - name: Build and push Retry Service
        uses: docker/build-push-action@v5
        with:
          context: ./retry-service
          push: true
          tags: yourdockerhub/retry-service:latest

      - name: Build and push Notification Storage
        uses: docker/build-push-action@v5
        with:
          context: ./notification-storage
          push: true
          tags: yourdockerhub/notification-storage:latest




