name: CD - Docker Build & Push (multi-service)

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker Builds
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build API Gateway JAR
        run: ./gradlew :api-gateway:build

      - name: Build Email Service JAR
        run: ./gradlew :email-service:build

      - name: Build SMS Service JAR
        run: ./gradlew :sms-service:build

      - name: Build Push Service JAR
        run: ./gradlew :push-service:build

      - name: Build Retry Service JAR
        run: ./gradlew :retry-service:build

      - name: Build Notification Storage JAR
        run: ./gradlew :notification-storage:build

      - name: Build and push API Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          push: true
          tags: javac168/api-gateway:latest

      - name: Build and push Email Service
        uses: docker/build-push-action@v5
        with:
          context: ./email-service
          push: true
          tags: javac168/email-service:latest

      - name: Build and push SMS Service
        uses: docker/build-push-action@v5
        with:
          context: ./sms-service
          push: true
          tags: javac168/sms-service:latest

      - name: Build and push Push Service
        uses: docker/build-push-action@v5
        with:
          context: ./push-service
          push: true
          tags: javac168/push-service:latest

      - name: Build and push Retry Service
        uses: docker/build-push-action@v5
        with:
          context: ./retry-service
          push: true
          tags: javac168/retry-service:latest

      - name: Build and push Notification Storage
        uses: docker/build-push-action@v5
        with:
          context: ./notification-storage
          push: true
          tags: javac168/notification-storage:latest
