name: monorepo-ci
on:
  pull_request:
  push:
    branches: [ master ]

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Unit & integration tests
        run: ./gradlew clean test --no-daemon
      - name: Publish JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: '**/build/test-results/test/*.xml'

  build-all:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17', cache: gradle }
      - run: chmod +x gradlew
      - name: Sanity build
        run: ./gradlew build -x test --no-daemon

  qodana:
    needs: test
    uses: ./.github/workflows/qodana_code_quality.yml
    secrets: inherit
